"""Codegen for the ``rewards/`` artefact directory.

Given a :class:`RewardBundle` and the source :class:`GoldenDocument`, this
module writes a self-contained directory that downstream users can drop into
their training repository:

    out_dir/rewards/
        __init__.py        # re-exports REWARDS and WEIGHTS
        rewards.py         # one ``reward_<name>`` function per spec
        reward_spec.yaml   # the bundle, for traceability
        _lib.py            # primitives copied verbatim from library.py

The generated module imports only the Python standard library plus
``jsonschema`` (already a runtime dependency of gyroscope) and the adjacent
``_lib`` module. It does **not** require gyroscope to be installed.
"""

from __future__ import annotations

import datetime as _dt
import logging
from collections.abc import Callable
from pathlib import Path
from typing import Any

from gyroscope.core.models import GoldenDocument, RewardKind, RewardSpec
from gyroscope.rewards import library as _library_module
from gyroscope.rewards.spec import RewardBundle

logger = logging.getLogger(__name__)

__all__ = [
    "RENDERERS",
    "emit_rewards_module",
    "register_renderer",
]


RendererFn = Callable[[RewardSpec], str]


_LIB_BANNER = (
    "# Self-contained reward primitives. Regenerated by the reward codegen.\n"
    "# Do not edit by hand - changes will be overwritten on the next run.\n"
)


def _read_library_source() -> str:
    """Slurp the library module's source for inlining."""
    src_path = Path(_library_module.__file__)
    return src_path.read_text(encoding="utf-8")


def _render_imports() -> str:
    return (
        "from __future__ import annotations\n\n"
        "import logging\n"
        "from typing import Any\n\n"
        "from . import _lib\n\n"
        "logger = logging.getLogger(__name__)\n\n"
    )


def _py_repr(value: Any) -> str:
    """Return a Python literal repr that round-trips for our config payloads."""
    return repr(value)


def _render_format_body(spec: RewardSpec) -> str:
    cfg = spec.config
    if "pattern" in cfg:
        return (
            f"    pattern = {_py_repr(cfg['pattern'])}\n"
            f"    return _lib.format_regex(completions, pattern=pattern)\n"
        )
    if "json_schema" in cfg:
        return (
            f"    schema = {_py_repr(cfg['json_schema'])}\n"
            f"    return _lib.format_json_schema(completions, schema=schema)\n"
        )
    sections = cfg.get("sections", [])
    return (
        f"    sections = {_py_repr(list(sections))}\n"
        f"    return _lib.format_sections(completions, sections=sections)\n"
    )


def _render_lexical_body(spec: RewardSpec) -> str:
    cfg = spec.config
    return (
        f"    required = {_py_repr(list(cfg.get('required', [])))}\n"
        f"    forbidden = {_py_repr(list(cfg.get('forbidden', [])))}\n"
        f"    case_sensitive = {_py_repr(bool(cfg.get('case_sensitive', False)))}\n"
        f"    return _lib.lexical(\n"
        f"        completions,\n"
        f"        required=required,\n"
        f"        forbidden=forbidden,\n"
        f"        case_sensitive=case_sensitive,\n"
        f"    )\n"
    )


def _render_length_body(spec: RewardSpec) -> str:
    cfg = spec.config
    return (
        f"    return _lib.length(\n"
        f"        completions,\n"
        f"        min_tokens={int(cfg.get('min_tokens', 0))},\n"
        f"        max_tokens={int(cfg.get('max_tokens', 1024))},\n"
        f"        sweet_spot={int(cfg.get('sweet_spot', 256))},\n"
        f"    )\n"
    )


def _render_citation_body(spec: RewardSpec) -> str:
    cfg = spec.config
    default_pattern = r"\[KNW-\d+\]"
    return (
        f"    return _lib.citation(\n"
        f"        completions,\n"
        f"        require_ids={_py_repr(bool(cfg.get('require_ids', True)))},\n"
        f"        min_citations={int(cfg.get('min_citations', 1))},\n"
        f"        id_pattern={_py_repr(cfg.get('id_pattern', default_pattern))},\n"
        f"    )\n"
    )


def _render_safety_body(spec: RewardSpec) -> str:
    cfg = spec.config
    return (
        f"    anti_pattern_terms = {_py_repr(list(cfg.get('anti_pattern_terms', [])))}\n"
        f"    return _lib.safety(completions, anti_pattern_terms=anti_pattern_terms)\n"
    )


def _render_principle_body(spec: RewardSpec) -> str:
    cfg = spec.config
    statement = cfg.get("principle_statement", "")
    return (
        f"    judge = kwargs.get('judge')\n"
        f"    principle_statement = {_py_repr(statement)}\n"
        f"    return _lib.principle_judge(\n"
        f"        completions,\n"
        f"        prompts,\n"
        f"        principle_statement=principle_statement,\n"
        f"        judge=judge,\n"
        f"    )\n"
    )


def _render_procedure_body(spec: RewardSpec) -> str:
    cfg = spec.config
    ordered_steps = list(cfg.get("ordered_steps", []))
    ordered = bool(cfg.get("ordered", True))
    return (
        f"    ordered_steps = {_py_repr(ordered_steps)}\n"
        f"    return _lib.procedure_check(\n"
        f"        completions,\n"
        f"        ordered_steps=ordered_steps,\n"
        f"        ordered={_py_repr(ordered)},\n"
        f"    )\n"
    )


def _render_noop_body(spec: RewardSpec) -> str:  # pragma: no cover - exhaustive fallback
    return "    return [0.0 for _ in completions]\n"


#: Mapping of :class:`RewardKind` -> body renderer. Plugins can extend this
#: via :func:`register_renderer`. Each renderer takes a ``RewardSpec`` and
#: returns the indented function body (the surrounding ``def`` / docstring
#: are built by :func:`_render_function`).
RENDERERS: dict[RewardKind, RendererFn] = {
    RewardKind.FORMAT: _render_format_body,
    RewardKind.LEXICAL: _render_lexical_body,
    RewardKind.LENGTH: _render_length_body,
    RewardKind.CITATION: _render_citation_body,
    RewardKind.SAFETY: _render_safety_body,
    RewardKind.PRINCIPLE: _render_principle_body,
    RewardKind.PROCEDURE: _render_procedure_body,
}


def register_renderer(kind: RewardKind, fn: RendererFn) -> None:
    """Register or replace the body renderer for ``kind``.

    Registering an existing kind overwrites the binding — tests and plugins
    can install a custom renderer without monkeypatching module internals.
    """
    RENDERERS[kind] = fn


def _render_function(spec: RewardSpec) -> str:
    """Emit a TRL-compatible reward function for a single spec."""
    fn_name = f"reward_{spec.name}"
    docstring = (
        f'"""{spec.description}\n\n'
        f"    Kind: {spec.kind.value}\n"
        f"    Weight: {spec.weight}\n"
        f"    Principle ids: {list(spec.principle_ids)}\n"
        f"    Procedure ids: {list(spec.procedure_ids)}\n"
        f'    """'
    )
    renderer = RENDERERS.get(spec.kind, _render_noop_body)
    body = renderer(spec)
    return (
        f"def {fn_name}(prompts: list[str], completions: list[str], **kwargs: Any) -> list[float]:\n"
        f"    {docstring}\n"
        f"{body}"
    )


def _render_rewards_py(bundle: RewardBundle, golden: GoldenDocument) -> str:
    when = _dt.datetime.now(_dt.UTC).isoformat(timespec="seconds")
    header = (
        f'"""Auto-generated reward functions for role: {bundle.golden_role}.\n\n'
        f"Generated at: {when}\n"
        f"Bundle version: {bundle.version}\n"
        f"Source identity: {golden.identity.role}\n\n"
        f"Specs ({len(bundle.specs)}):\n"
    )
    for s in bundle.specs:
        header += f"  - {s.name} ({s.kind.value}, weight={s.weight})\n"
    header += (
        "\nEach function follows the TRL GRPOTrainer signature:\n"
        "    reward(prompts, completions, **kwargs) -> list[float]\n"
        "Scores are clipped to [0.0, 1.0]. The module exposes REWARDS (list of\n"
        "callables) and WEIGHTS (mapping of name to weight).\n"
        '"""\n\n'
    )

    parts: list[str] = [header, _render_imports()]
    for spec in bundle.specs:
        parts.append(_render_function(spec))
        parts.append("\n\n")

    names = [f"reward_{s.name}" for s in bundle.specs]
    parts.append("REWARDS = [\n")
    for n in names:
        parts.append(f"    {n},\n")
    parts.append("]\n\n")

    parts.append("WEIGHTS = {\n")
    for s in bundle.specs:
        parts.append(f"    {s.name!r}: {float(s.weight)},\n")
    parts.append("}\n")

    return "".join(parts)


def _render_init_py(bundle: RewardBundle) -> str:
    lines = [
        '"""Generated reward package."""',
        "",
        "from .rewards import REWARDS, WEIGHTS",
        "",
        "__all__ = [\"REWARDS\", \"WEIGHTS\"]",
        "",
        f"BUNDLE_VERSION = {bundle.version!r}",
        f"GOLDEN_ROLE = {bundle.golden_role!r}",
        "",
    ]
    return "\n".join(lines)


def emit_rewards_module(
    bundle: RewardBundle,
    golden: GoldenDocument,
    out_dir: Path | str,
) -> Path:
    """Write the generated ``rewards/`` directory and return ``rewards.py``."""
    out_dir = Path(out_dir)
    pkg_dir = out_dir / "rewards"
    pkg_dir.mkdir(parents=True, exist_ok=True)

    # 1) Inline copy of library primitives. The banner is a `#` comment block
    # so the original module's ``from __future__`` import stays at the top.
    lib_src = _read_library_source()
    (pkg_dir / "_lib.py").write_text(_LIB_BANNER + lib_src, encoding="utf-8")

    # 2) rewards.py
    rewards_path = pkg_dir / "rewards.py"
    rewards_path.write_text(_render_rewards_py(bundle, golden), encoding="utf-8")

    # 3) reward_spec.yaml
    bundle.to_yaml(pkg_dir / "reward_spec.yaml")

    # 4) __init__.py
    (pkg_dir / "__init__.py").write_text(_render_init_py(bundle), encoding="utf-8")

    logger.info(
        "wrote generated reward package to %s (%d specs)",
        pkg_dir,
        len(bundle.specs),
    )
    return rewards_path
